Hr_SystemProject/Controllers/SalaryController.cs
using Hr_SystemProject.ViewModel;
using HR_SystemProject.Models;
using HR_SystemProject.Repositories;
using HR_SystemProject.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Hr_SystemProject.Controllers
{
    public class SalaryController : Controller
    {
        IAttendanceRepository AttendanceRepository;
        IEmployeeRepository EmployeeRepository;
        IGeneralSettingsRepository GeneralSettingsRepository;
        public SalaryController(IEmployeeRepository EmpRepo, IAttendanceRepository AttendanceRepo, IGeneralSettingsRepository GeneralSettingsRepo)
        {
            AttendanceRepository = AttendanceRepo;
            EmployeeRepository = EmpRepo;
            GeneralSettingsRepository = GeneralSettingsRepo;
        }
        [Authorize("Permissions.SalaryController.Show")]
        public IActionResult Show()
        {
            List<Employee> Employees = EmployeeRepository.GetAll();
            List<Attendence> attendences = new List<Attendence>();
            List<SalaryViewModel> salarys = new List<SalaryViewModel>();
            int addperhour = GeneralSettingsRepository.GetFirst().Bouns;
            int subperhour = GeneralSettingsRepository.GetFirst().Discount;

            foreach (var emp in Employees)
            {
                
                TimeSpan AddedTime = TimeSpan.Zero;
                TimeSpan SubedTime = TimeSpan.Zero;
                attendences = AttendanceRepository.GetById(emp.ID);
                decimal AllAdds = 0;
                decimal AllSubs = 0;
                int abscence = 0;
                foreach (Attendence attenden in attendences)
                {
                    if(attenden.checkIn > emp.checkIn)
                    {
                        SubedTime+= (attenden.checkIn - emp.checkIn);
                    }
                    if(attenden.checkOut > emp.checkOut)
                    {
                        AddedTime += (attenden.checkOut - emp.checkOut);
                    }                  
                    
                }
                //DaysInMonth Function Get Number of Days In Certain Month.
                for (int day = 1; day <= DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month); day++)
                {
                    DateOnly date = new DateOnly(DateTime.Now.Year, DateTime.Now.Month, day);
                    string DayName = date.DayOfWeek.ToString();
                    string vacation1 = Enum.GetName(typeof(WeekDays), GeneralSettingsRepository.GetFirst().vacation1);
                    string vacation2 = Enum.GetName(typeof(WeekDays), GeneralSettingsRepository.GetFirst().vacation2);
                    bool attended = attendences.Exists(e => e.date == date);
                    if ( vacation1!= DayName && vacation2!= DayName && !attended)
                    {
                        abscence++;
                    }
                }
                AllAdds = (decimal)(AddedTime.TotalHours * addperhour);
                AllSubs = (decimal)(SubedTime.TotalHours * subperhour);
                salarys.Add(new SalaryViewModel() 
                { Name=emp.name,
                  AbscenceNumber=abscence,
                  AttendanceNumber=attendences.Count,
                  Salary=emp.salary,
                  Department = emp.department.Name,
                  AddTime = AddedTime.TotalHours,
                  SubTime = SubedTime.TotalHours,
                  AllAdd = AllAdds,
                  AllSub = -AllSubs - abscence * (emp.salary / DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month)),
                  OverallSalary = emp.salary + AllAdds + (-AllSubs) - abscence*(emp.salary/ DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month))
                });
            }
     
            
            return View(salarys);
        }
        //[Authorize("Permissions.SalaryController.Search")]
        public IActionResult Search(string searchText, int month,  int year)
        {

            List<Employee> Employees = EmployeeRepository.GetAll();
            if (searchText != null)
            {
                Employees = Employees.Where(a => a.name.ToLower().Contains(searchText.ToLower())).ToList();
            }
            List<Attendence> attendences = new List<Attendence>();
            List<SalaryViewModel> salarys = new List<SalaryViewModel>();
            int addperhour = GeneralSettingsRepository.GetFirst().Bouns;
            int subperhour = GeneralSettingsRepository.GetFirst().Discount;

            foreach (var emp in Employees)
            {
                TimeSpan AddedTime = TimeSpan.Zero;
                TimeSpan SubedTime = TimeSpan.Zero;
                attendences = AttendanceRepository.GetById(emp.ID);
                attendences = attendences.Where(a=>a.date.Month==month&&a.date.Year==year).ToList();
                
                decimal AllAdds = 0;
                decimal AllSubs = 0;
                int abscence = 0;
                foreach (Attendence attenden in attendences)
                {
                    if (attenden.checkIn > emp.checkIn)
                    {
                        SubedTime += (attenden.checkIn - emp.checkIn);
                    }
                    if (attenden.checkOut > emp.checkOut)
                    {
                        AddedTime += (attenden.checkOut - emp.checkOut);
                    }

                }
                //DaysInMonth Function Get Number of Days In Certain Month.
                for (int day = 1; day <= DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month); day++)
                {
                    DateOnly date = new DateOnly(DateTime.Now.Year, DateTime.Now.Month, day);
                    string DayName = date.DayOfWeek.ToString();
                    string vacation1 = Enum.GetName(typeof(WeekDays), GeneralSettingsRepository.GetFirst().vacation1);
                    string vacation2 = Enum.GetName(typeof(WeekDays), GeneralSettingsRepository.GetFirst().vacation2);
                    bool attended = attendences.Exists(e => e.date == date);
                    if (vacation1 != DayName && vacation2 != DayName && !attended)
                    {
                        abscence++;
                    }
                }
                AllAdds = (decimal)(AddedTime.TotalHours * addperhour);
                AllSubs = (decimal)(SubedTime.TotalHours * subperhour);
                salarys.Add(new SalaryViewModel()
                {
                    Name = emp.name,
                    AbscenceNumber = abscence,
                    AttendanceNumber = attendences.Count,
                    Salary = emp.salary,
                    Department = emp.department.Name,
                    AddTime = AddedTime.TotalHours,
                    SubTime = SubedTime.TotalHours,
                    AllAdd = AllAdds,
                    AllSub = -AllSubs - abscence * (emp.salary / DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month)),
                    OverallSalary = emp.salary + AllAdds + (-AllSubs) - abscence * (emp.salary / DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month))
                });
            }
     
            
            return PartialView("_SalaryTablePartial", salarys);

        }
    }
}

Hr_SystemProject/Views/Salary/Show.cshtml
@using System.Globalization
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
@{
    ViewData["Title"] = "Show";
    var months = Enumerable.Range(1, 12).Select(i => new
    {
        A = i,
        B = DateTimeFormatInfo.CurrentInfo.GetMonthName(i)
    });
}

<h1>Salary Report</h1>
<div class="row mb-3">
    <div class="col-sm-12">
        <div class="form-inline pull-right">
            <label>Search</label>
            <input type="text" class="form-control" id="searchtxt" placeholder="Search by Name or Department" />
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-md-4">
            <label class="form-label">Year</label>
            <select class="form-control" id="yearbox">
            <option selected disabled>Select Year...</option>
            @for(int i= DateTime.Now.Year-10; i<=DateTime.Now.Year; i++)
            {
                @if (i==DateTime.Now.Year)
                {
                        <option value="@i" selected>@i</option>
                }else{
                        <option value="@i">@i</option>
                }
                
            }
            </select>
        </div>
        <div class="col-md-4">
            <label class="form-label">Month</label>
            <select class="form-control" id="monthbox">
            <option selected disabled>Select Month...</option>
            @foreach(var month in months)
            {
                    @if (month.A == DateTime.Now.Month)
                    {
                        <option value="@month.A" selected>@month.B.ToString()</option>
                    }else{
                        <option value="@month.A">@month.B.ToString()</option>
                    }
                
            }
            </select>
        </div>
    </div>
</div>
<div id="salaryTable"></div>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

<script>
    $(() => {
        getSalary();

        $('#searchtxt').on('keyup', () => {
            getSalary();
        });
        $('#yearbox').on('change', () => {
            getSalary();
        });
        $('#monthbox').on('change', () => {
            getSalary();
        });
    });

    function getSalary() {
        $.ajax({
            url: '@Url.Action("Search", "Salary")',
            datatype: 'html',
            method: 'GET',
            data: { searchText: $('#searchtxt').val(), year: $('#yearbox').val(), month: $('#monthbox').val() },
            success: function (res) {
                $('#salaryTable').html('').html(res);
                console.log(res);
            },
            error: function (err) {
                console.log(err);
            }
        })
    }
</script>

Hr_SystemProject/Views/Salary/_SalaryTablePartial.cshtml
@using Hr_SystemProject.ViewModel
@using Microsoft.AspNetCore.Authorization

@model List<SalaryViewModel>
@inject IAuthorizationService AuthorizationService
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = null;
}
<table class="table">
    <thead>
        <tr>
            <th scope="col">EmpName</th>
            <th scope="col">Department</th>
            <th scope="col">Salary</th>
            <th scope="col">AttendDays</th>
            <th scope="col">AbsenceDays</th>
            <th scope="col">AddTime</th>
            <th scope="col">SubTime</th>
            <th scope="col">AllAdd</th>
            <th scope="col">AllSub</th>
            <th scope="col">OverallSalary</th>
        </tr>

    </thead>
    <tbody>
        @foreach (var item in @Model)
        {
            <tr>
                <td scope="row">@item.Name</td>
                <td scope="row">@item.Department</td>
                <td scope="row">@item.Salary</td>
                <td scope="row">@item.AttendanceNumber</td>
                <td scope="row">@item.AbscenceNumber</td>
                <td scope="row">@item.AddTime.ToString("0.##")</td>
                <td scope="row">@item.SubTime.ToString("0.##")</td>
                <td scope="row">@item.AllAdd.ToString("0.##")</td>
                <td scope="row">@item.AllSub.ToString("0.##")</td>
                <td scope="row">@item.OverallSalary.ToString("0.##")</td>
            </tr>

        }
    </tbody>

</table>