Hr_SystemProject/Models/GeneralSettings.cs
namespace HR_SystemProject.Models
{
    public class GeneralSettings
    {
        public int ID { get; set; }
        public int Bouns { get; set; }
        public int Discount { get; set; }
        public int vacation1 { get; set; }
        public int vacation2 { get; set; }
    }
}

Hr_SystemProject/Controllers/GeneralSettingsController.cs
using HR_SystemProject.Repositories;
using HR_SystemProject.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HR_SystemProject.Controllers
{
    public class GeneralSettingsController : Controller
    {
        IGeneralSettingsRepository GeneralSettingsRepo;
        public GeneralSettingsController(IGeneralSettingsRepository GeneralSetRepo)
        {
            GeneralSettingsRepo = GeneralSetRepo;
        }
        [HttpGet]
        [Authorize("Permissions.GeneralSettingsController.Update")]
        public IActionResult Update()
        {
            GeneralSettingsViewModel generalSettingsViewModel = new GeneralSettingsViewModel();
            return View(generalSettingsViewModel);
        }

        [HttpPost]
        public IActionResult Save(GeneralSettingsViewModel generalSettingsView)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    GeneralSettingsRepo.Update(generalSettingsView);
                    TempData["message"] = "Added Successfully";
                    TempData["AddClass"] = "success";
                    return View("Update");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(String.Empty, ex.Message.ToString());
                    return View("Update");

                }

            }
            else
            {
                TempData["message"] = "There's a problem. Please Check What you entered again.";
                TempData["AddClass"] = "danger";
                return View("Update");
            }
        }
    }
}

Hr_SystemProject/Views/GeneralSettings/Update.cshtml
@using HR_SystemProject.ViewModel
@model GeneralSettingsViewModel

@{
    ViewData["Title"] = "Update";
}

<h1>General Settings</h1>
<form method="post" asp-controller="GeneralSettings" asp-action="Save" type="text">
    <div class="row mb-3">
        <div class="col-md-4">
            <label asp-for="@Model.Bouns" class="form-label"></label>
            <input asp-for="@Model.Bouns" class="form-control" />
            <span asp-validation-for="@Model.Bouns" class="text-danger"></span>
        </div>

        <div class="col-md-4">
            <label asp-for="@Model.Discount" class="form-label"></label>
            <input asp-for="@Model.Discount" class="form-control" />
            <span asp-validation-for="@Model.Discount" class="text-danger"></span>
        </div>
    </div>
    <div class="row mb-3 ms-1">
        <div class="col-md-4">
            <label asp-for="@Model.vacation1" class="form-label"></label>
            <select class="form-select" asp-for="@Model.vacation1" asp-items="Html.GetEnumSelectList<WeekDays>()">
                <option selected disabled> --Select--</option>
            </select>
            <span asp-validation-for="@Model.vacation1" class="text-danger"></span>
        </div>

        <div class="col-md-4">
            <label asp-for="vacation2" class="form-label"></label>
            <select class="form-select" asp-for="@Model.vacation2" asp-items="Html.GetEnumSelectList<WeekDays>()">
                <option selected disabled>--Select--</option>
            </select>
            <span asp-validation-for="@Model.vacation2" class="text-danger"></span>
        </div>
    </div>
    <div class="col-12 mt-2">
        <button type="submit" class="btn btn-primary">Update</button>
    </div>
</form>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>